spring:
  application:
    name: flipkart-backend
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:mem:flipkart
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.flipkart.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: flipkartSecretKey2024ForJWTTokenGeneration
  expiration: 86400000 # 24 hours in milliseconds

cors:
  allowed-origins: http://localhost:5173,http://localhost:5174,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
